import{useEffect,useState}from'react';import{Link}from'react-router-dom';import{api}from'../api/client';
export default function Home({user}){
 const[p,setP]=useState();const[recent,setRecent]=useState([]);
 useEffect(()=>{Promise.all([api('/player/progression'),api('/player/matches?limit=5')]).then(([a,b])=>{setP(a);setRecent(b)}).catch(()=>{})},[]);
 const level=p?.level??user.level??1,xp=p?.xp??user.xp??0,current=p?.current_xp??xp%100,streak=p?.current_streak??0;
 return <div className="page home-page">
  <section className="hero hero-game-v7"><div className="hero-copy"><span className="eyebrow">⚡ CENTRAL DO JOGADOR</span><h1>Seu faro.<br/><span>Sua estratégia.</span><br/>Sua vitória.</h1><p>Entre na Arena, descubra os cards dos adversários e transforme cada duelo em reputação.</p><div className="hero-actions"><Link className="primary big-btn" to="/torneios">⚔️ Entrar na Arena</Link><Link className="ghost-btn" to="/ranking">Ver ranking →</Link></div><div className="trust-row"><span>🛡️ Servidor valida cada jogada</span><span>⚡ Duelos rápidos</span><span>🏆 Carreira competitiva</span></div></div>
   <div className="hero-showcase-v7"><div className="hero-orbit"></div><div className="hero-card-back"><span>?</span><small>CARD OCULTO</small></div><div className="hero-card-front"><div><span>CAÇADOR</span><b>{user.username}</b></div><strong><span className="farejador-coin" aria-hidden="true">F</span> {user.balance}</strong><small>⭐ Nível {level} · {user.points} pts</small><div className="mini-xp"><i style={{width:`${current}%`}}/></div></div><div className="hero-duel-pill">⚔️ PRONTO PARA O DUELO</div></div>
  </section>
  <section className="player-dashboard"><div className="player-dashboard-main"><div><span className="eyebrow">🔥 SEU MOMENTO</span><h2>{streak?`${streak} vitórias seguidas`:'Sua primeira sequência começa agora'}</h2><p>{streak?'Você está em alta. Continue antes que a chama apague.':'Entre em uma batalha e comece a construir sua carreira.'}</p></div><div className="dashboard-level"><span>NÍVEL {level}</span><b>{current}/100 XP</b><div><i style={{width:`${current}%`}}/></div></div></div><div className="quick-metrics"><div><b>⚔️ {p?.matches??0}</b><small>DUELOS</small></div><div><b>🏆 {p?.wins??0}</b><small>VITÓRIAS</small></div><div><b>🎯 {p?.win_rate??0}%</b><small>APROVEITAMENTO</small></div><div><b>🔥 {streak}</b><small>SEQUÊNCIA</small></div></div></section>
  <section className="section-head"><div><span className="eyebrow">COMO FUNCIONA</span><h2>Você joga. A Arena cuida do resto.</h2></div></section>
  <section className="feature-grid"><Link to="/torneios" className="feature-card feature-main"><div className="feature-icon">⚔️</div><span>01 · ARENA</span><h3>Escolha seu torneio</h3><p>Veja inscrições, jogadores, prêmio e relógio em uma experiência feita para decidir rápido.</p><b>Explorar torneios →</b></Link><Link to="/saldo" className="feature-card"><div className="feature-icon gold">🪙</div><span>02 · ECONOMIA</span><h3>Construa seu saldo</h3><p>Farejadores, XP e histórico ficam centralizados na sua carteira.</p><b>Ver carteira →</b></Link><Link to="/ranking" className="feature-card"><div className="feature-icon purple">♛</div><span>03 · REPUTAÇÃO</span><h3>Suba no ranking</h3><p>Vitórias e desempenho alimentam sua trajetória competitiva.</p><b>Ver ranking →</b></Link></section>
  <section className="recent-strip"><div><span className="eyebrow">⚔️ ÚLTIMAS BATALHAS</span><h2>Seu histórico está vivo</h2></div><div className="recent-list">{recent.map(x=><Link to={`/torneios/${x.tournament_public_id}`} key={x.match_id}><span>{x.result==='win'?'🏆':x.result==='loss'?'❌':x.result==='draw'?'🤝':'⏳'}</span><div><b>{x.tournament_title}</b><small>vs {x.opponent||'BYE'}</small></div><strong>{x.result==='win'?'+ VITÓRIA':x.result==='loss'?'DERROTA':'EM ANDAMENTO'}</strong></Link>)}{!recent.length&&<span className="muted">Seus primeiros duelos aparecerão aqui.</span>}</div></section>
  <section className="home-strip"><div><span className="eyebrow">🚀 PRÓXIMO PASSO</span><h2>Pronto para descobrir alguém?</h2><p>Abra a Arena e encontre uma edição esperando por você.</p></div><Link className="primary" to="/torneios">Encontrar duelo →</Link></section>
 </div>
}
