import{useEffect,useState}from'react';import{Link}from'react-router-dom';import{api}from'../api/client';
function fmt(s){if(!s)return'—';return new Date(s).toLocaleString()}
function initials(name=''){return name.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'?'}
const icons={first_tournament:'🎟️',first_win:'🎯',first_title:'🏆',five_wins:'🔥',ten_matches:'⚔️',twenty_five_matches:'💎',fifty_wins:'👑',ten_titles:'🧠'};
export default function Profile(){
 const[p,setP]=useState(),[a,setA]=useState([]),[h,setH]=useState([]),[m,setM]=useState([]),[stats,setStats]=useState(),[season,setSeason]=useState(),[prog,setProg]=useState();
 async function load(){try{const[x,y,z,q,r,s,g]=await Promise.all([api('/player/profile'),api('/player/achievements'),api('/player/history?limit=20'),api('/player/matches?limit=20'),api('/player/stats'),api('/player/season'),api('/player/progression')]);setP(x);setA(y);setH(z);setM(q);setStats(r);setSeason(s);setProg(g)}catch{}}
 useEffect(()=>{load()},[]);
 if(!p)return <div className="page"><div className="empty">Carregando seu perfil...</div></div>;
 const level=Number(prog?.level??p.level??1),xp=Number(prog?.xp??p.xp??0),currentXp=Number(prog?.current_xp??xp%100),xpPct=currentXp, titles=Number(p.stats?.titles||0),wins=Number(stats?.wins||0),matches=Number(stats?.matches||0),winRate=Number(stats?.win_rate||0);
 return <div className="page profile-page">
  <section className="profile-hero-v7"><div className="profile-identity"><div className="profile-avatar-v7">{initials(p.username)}</div><div><span className="eyebrow">👤 CAÇADOR · NÍVEL {level}</span><h1>{p.username}</h1><p>Sua carreira, seu faro e tudo o que você conquistou na Arena.</p><div className="streak-chip">🔥 {prog?.current_streak||0} vitórias seguidas <span>·</span> melhor {prog?.best_streak||0}</div></div></div><div className="level-card-v7"><div className="level-top"><span>NÍVEL {level}</span><b>{currentXp}/100 XP</b></div><div className="xp-track"><div className="xp-fill" style={{width:`${xpPct}%`}}/></div><small>{prog?.xp_to_next||100} XP para o próximo nível</small><strong>⭐ {xp} XP total</strong></div></section>
  <section className="career-grid-v7"><div className="career-card gold"><span><span className="farejador-coin" aria-hidden="true">F</span></span><b>{p.balance}</b><small>FAREJADORES</small></div><div className="career-card"><span>⚡</span><b>{p.xp}</b><small>XP TOTAL</small></div><div className="career-card"><span>🏆</span><b>{p.points}</b><small>PONTOS</small></div><div className="career-card"><span>👑</span><b>{titles}</b><small>TÍTULOS</small></div></section>
  <section className="profile-highlight-row"><div><span className="eyebrow">🔥 MOMENTO ATUAL</span><h2>{prog?.current_streak?`${prog.current_streak} vitórias consecutivas`:'Comece sua sequência'}</h2><p>{prog?.current_streak?'Não deixe a chama apagar.':'A próxima vitória começa sua sequência.'}</p></div><div className="streak-big">🔥<b>{prog?.current_streak||0}</b><small>SEQUÊNCIA</small></div></section>
  {stats&&<section className="panel premium-panel"><div className="section-head"><div><span className="eyebrow">📈 PERFORMANCE</span><h2>Seu desempenho</h2></div><span>{winRate}% de aproveitamento</span></div><div className="profile-grid compact"><div><b>{stats.matches}</b><small>Duelos</small></div><div><b>{stats.wins}</b><small>Vitórias</small></div><div><b>{stats.losses}</b><small>Derrotas</small></div><div><b>{stats.draws}</b><small>Empates</small></div></div></section>}
  <section className="panel premium-panel"><div className="section-head"><div><span className="eyebrow">🏅 COLEÇÃO</span><h2>Conquistas</h2></div><span>{a.filter(x=>x.unlocked).length}/{a.length}</span></div><div className="achievements-v7">{a.map(x=><article className={x.unlocked?'unlocked':''} key={x.code}><div className="achievement-icon">{icons[x.code]||'🏅'}</div><div><b>{x.name}</b><span>{x.description}</span><small>{x.unlocked?`✓ Desbloqueada · +${x.xp_reward} XP`:`🔒 +${x.xp_reward} XP ao desbloquear`}</small></div></article>)}</div></section>
  {season&&<section className="season-banner"><div><span className="eyebrow">🔥 TEMPORADA ATIVA</span><h2>{season.name}</h2><p>Seu ranking da temporada é calculado separadamente do ranking geral.</p></div><Link className="primary" to="/ranking">Ver ranking →</Link></section>}
  <section className="panel premium-panel"><div className="section-head"><div><span className="eyebrow">⚔️ ÚLTIMOS DUELOS</span><h2>Seu histórico recente</h2></div><Link to="/torneios">Ir para Arena →</Link></div>{m.map(x=><div className="ledger-row" key={x.match_id}><span><b>{x.result==='win'?'🏆':x.result==='loss'?'❌':x.result==='draw'?'🤝':'⏳'} {x.tournament_title}</b><small>vs {x.opponent||'BYE'} · rodada {x.round} · {x.status}</small></span><Link to={'/torneios/'+x.tournament_public_id}>{x.status==='pending'&&x.is_my_turn?'Responder →':'Ver Arena →'}</Link></div>)}{!m.length&&<p className="muted">Nenhum confronto ainda.</p>}</section>
  <section className="panel premium-panel"><div className="section-head"><div><span className="eyebrow">👑 PALMARÉS</span><h2>Histórico de torneios</h2></div></div>{h.map((x,i)=><div className="ledger-row" key={x.tournament_id+'-'+x.position+'-'+i}><span>{x.title}<small>{x.position}º lugar</small></span><b>+{x.points} pts · +{x.xp} XP</b></div>)}{!h.length&&<p className="muted">Você ainda não possui resultados.</p>}</section>
 </div>
}
