import{useEffect,useState}from'react';
import{Link,useParams}from'react-router-dom';
import{api,getToken}from'../api/client';

function clock(s){s=Math.max(0,Number(s||0));const m=Math.floor(s/60),sec=s%60;return `${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}`}
function initials(name='?'){return String(name).slice(0,2).toUpperCase()}
function statusLabel(status){return({open:'INSCRIÇÕES ABERTAS',live:'AO VIVO',finished:'FINALIZADO',cancelled:'CANCELADO'}[status]||status)}
function resultReasonLabel(x){return({all_attempts_exhausted:'Ataques esgotados',opponent_card_guessed:'Card descoberto',card_guessed:'Card descoberto',timeout:'Tempo esgotado',no_show:'Ausência do adversário',technical_no_show:'Ausência do adversário',timeout_no_show:'Tempo esgotado',timeout_card_score:'Tempo esgotado',replay:'Empate · replay',replay_empate:'Empate · replay',draw:'Empate',card_score:'Pontuação do card',bye:'Avanço automático'}[x]||x||'Duelo encerrado')}
function eventName(x){return({tournament_created:'Torneio criado',tournament_created_from_config:'Torneio criado da configuração',card_created:'Card criado',player_joined:'Participante entrou',registration_filled:'Torneio lotado',tournament_started:'Torneio iniciado',round_started:'Nova rodada',card_guess_submitted:'Resposta enviada',match_replay:'Empate · replay iniciado',match_finished:'Duelo finalizado',tournament_cancelled:'Torneio cancelado',tournament_finished:'Torneio finalizado'}[x]||x)}

export default function Room({user}){
 const{id}=useParams(),[t,setT]=useState(),[msg,setMsg]=useState(''),[tab,setTab]=useState('arena'),[selected,setSelected]=useState([]),[cardId,setCardId]=useState(''),[guess,setGuess]=useState(''),[events,setEvents]=useState([]),[lastGuess,setLastGuess]=useState(null),[attackFx,setAttackFx]=useState(null),[attacking,setAttacking]=useState(false);
 async function load(){try{const[detail,ev]=await Promise.all([api(`/tournaments/${id}`),api(`/tournaments/${id}/events?limit=60`)]);setT(detail);setEvents(ev)}catch(e){setMsg(e.message)}}
 useEffect(()=>{load();const x=setInterval(load,2000);return()=>clearInterval(x)},[id]);
 useEffect(()=>{let ws;try{const proto=location.protocol==='https:'?'wss':'ws';ws=new WebSocket(`${proto}://${location.host}/ws/tournaments/${id}?token=${encodeURIComponent(getToken()||'')}`);ws.onmessage=load}catch{}return()=>ws?.close()},[id]);
 if(!t)return <div className="page"><div className="empty">{msg||'Preparando sua Arena...'}</div></div>;

 const my=t.my_matches?.[0], latest=t.my_latest_match, state=t.my_tournament_state||{},deadline=my?.deadline?Math.max(0,Math.floor((new Date(my.deadline)-Date.now())/1000)):0;
 const reg=Math.max(0,Number(t.seconds_to_registration_end??0)),start=Math.max(0,Number(t.seconds_to_start??0)),cr=t.card_rules||{},options=cr.available_options||[],own=my?.my_attempts||[],used=own.map(x=>x.option);
 const isParticipant=Boolean(t.participants?.some(p=>String(p.user_id)===String(user?.id))),myCard=t.my_card,full=t.status==='open'&&(t.participant_count??0)>=(t.max_players??0);
 const isPlayer1=Boolean(my&&user&&String(my.player1_id)===String(user.id));
 const meName=my?(isPlayer1?my.player1:my.player2):(user?.username||'Você');
 const opponent=my?(isPlayer1?my.player2:my.player1):(latest?(String(latest.player1_id)===String(user?.id)?latest.player2:latest.player1):'Oponente');
 const readyToJoin=Boolean(cardId||t.available_cards?.length||myCard);
 const canBuild=t.status==='open'&&!isParticipant;
 function toggle(o){setSelected(v=>v.includes(o)?v.filter(x=>x!==o):v.length<cr.quantity_options?[...v,o]:v)}
 async function createCard(){try{if(selected.length!==cr.quantity_options)throw Error(`Escolha exatamente ${cr.quantity_options} opções.`);const r=await api(`/tournaments/${id}/cards`,{method:'POST',body:JSON.stringify({selected_options:selected})});setCardId(r.card_id);setSelected([]);setMsg('🎴 Seu card está pronto. Agora você já pode participar desta edição.');await load()}catch(e){setMsg(e.message)}}
 async function join(){try{const cid=cardId||t.available_cards?.[0]?.card_id||t.my_card?.card_id;if(!cid)throw Error('Crie ou selecione um card antes de participar.');const r=await api(`/tournaments/${id}/join`,{method:'POST',body:JSON.stringify({card_id:cid})});setMsg(`🎟️ Participação confirmada. Você já está na disputa. Saldo: ${r.balance} Farejadores.`);await load()}catch(e){setMsg(e.message)}}
 async function sendGuess(e){e.preventDefault();if(attacking||!my)return;try{if(!guess)throw Error('Escolha uma opção.');const answer=guess;setAttacking(true);setAttackFx('launch');const result=await api(`/tournaments/${id}/matches/${my.match_id}/guess`,{method:'POST',body:JSON.stringify({option:answer})});setLastGuess(answer);setGuess('');const latestAttempt=result?.my_matches?.[0]?.my_attempts?.slice(-1)?.[0];setAttackFx(latestAttempt?.correct?'hit':'miss');setMsg(latestAttempt?.correct?'🎯 ACERTO! Você encontrou uma opção do card.':'💨 ERRO! Essa opção não estava no card.');setTimeout(()=>setAttackFx(null),900);await load()}catch(e){setAttackFx('error');setMsg(e.message);setTimeout(()=>setAttackFx(null),900)}finally{setAttacking(false)}}
 const isLive=t.status==='live'&&my,attemptsLeft=my?.my_attempts_remaining??0;
 const stateClass={replay:'replay',eliminated:'eliminated',advanced:'advanced',finished:'finished',duel:'duel',registered:'registered'}[state.state]||'';
 const showState=Boolean(isParticipant&&state.state&&state.state!=='spectator');
 const finishedMatch=latest?.status==='finished'?latest:null;
 const matchWon=Boolean(finishedMatch&&String(finishedMatch.winner_id)===String(user?.id));
 const matchDraw=Boolean(finishedMatch&&(!finishedMatch.winner_id||['draw','replay','replay_empate'].includes(finishedMatch.result_reason)));
 const resultTitle=matchDraw?'EMPATE!':matchWon?'VOCÊ VENCEU!':'VOCÊ FOI ELIMINADO';
 const resultIcon=matchDraw?'🤝':matchWon?'🏆':'💥';
 return <div className="page arena-page">
  <Link to="/torneios" className="back">← Voltar para a Arena</Link>
  <header className="arena-head arena-head-premium">
   <div><div className="live-kicker"><span className={t.status==='live'?'live-dot':''}></span>{statusLabel(t.status)}</div><h1>{t.title}</h1><p>{cr.theme_name||String(t.category||'').replaceAll('_',' ')} <i>·</i> {cr.quantity_options} escolhas <i>·</i> {cr.quantity_answers} ataques</p></div>
   <div className="arena-prize"><small>PRÊMIO TOTAL</small><strong>{t.prize_pool}</strong><span><span className="farejador-coin" aria-hidden="true">F</span> Farejadores</span></div>
  </header>
  <div className="arena-tabs">{[['arena','⚔️ Arena'],['bracket','🏆 Chave'],['players','👥 Jogadores'],['results','📊 Resultado'],['timeline','🕒 Histórico']].map(([key,label])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{label}</button>)}</div>

  {tab==='arena'&&<div className="arena-grid">
   <section className="panel main-arena">
    <div className="arena-status"><div><span className={`status-pill ${t.status}`}>{t.status==='live'?'● AO VIVO':t.status==='finished'?'✓ FINALIZADO':'● INSCRIÇÕES'}</span><b>{t.participant_count}/{t.max_players}</b> jogadores</div><span>{t.status==='live'?'A Arena atualiza automaticamente':'Próxima etapa automática'}</span></div>

    {showState&&<section className={`player-state-banner ${stateClass}`}><div className="player-state-icon">{state.state==='replay'?'🤝':state.state==='eliminated'?'💥':state.state==='advanced'?'🏆':state.state==='finished'?'🎖️':state.state==='duel'?'⚔️':'🎟️'}</div><div><span className="eyebrow">SEU STATUS NA EDIÇÃO</span><h2>{state.state==='replay'?'REPLAY ATIVO':state.state==='eliminated'?'VOCÊ FOI ELIMINADO':state.state==='advanced'?'VOCÊ AVANÇOU':state.state==='finished'?'TORNEIO ENCERRADO':state.state==='duel'?'SEU DUELO ESTÁ ATIVO':'INSCRIÇÃO CONFIRMADA'}</h2><p>{state.message}</p>{state.state==='replay'&&<strong>👉 O que fazer agora: aguarde sua vez e jogue novamente. O empate não elimina ninguém.</strong>}{state.state==='eliminated'&&<strong>👉 O que fazer agora: acompanhe a classificação ou volte à Arena para disputar a próxima edição.</strong>}{state.state==='advanced'&&<strong>👉 O que fazer agora: acompanhe a chave. Sua próxima partida será liberada automaticamente.</strong>}</div><button className="state-action" onClick={()=>setTab(state.state==='eliminated'||state.state==='finished'?'results':state.state==='advanced'||state.state==='replay'?'bracket':'arena')}>{state.action||'VER DETALHES'} →</button></section>}

    {t.status==='open'&&reg>0&&canBuild&&<div className="join-box card-builder">
      <div className="builder-title"><div className="builder-icon">🎴</div><div><span className="eyebrow">1 · PREPARE SEU ATAQUE</span><h2>Monte seu card secreto</h2><p>Escolha <b>{cr.quantity_options}</b> opções entre <b>{options.length}</b>. Elas ficarão escondidas e serão usadas contra seu adversário.</p></div></div>
      <div className="builder-progress"><span><b>{selected.length}/{cr.quantity_options}</b> escolhidas</span><span>{selected.length===cr.quantity_options?'✓ Card pronto para bloquear':'Escolha as opções abaixo'}</span></div>
      <div className="card-preview-row">{Array.from({length:cr.quantity_options||2},(_,i)=><div className={`secret-slot ${selected[i]?'filled':''}`} key={i}>{selected[i]?<><small>OPÇÃO {i+1}</small><b>{selected[i]}</b><em>✓ SELECIONADA</em></>:<><span>?</span><small>ESCOLHA {i+1}</small></>}</div>)}</div>
      <div className="card-options">{options.map(o=><button type="button" className={selected.includes(o)?'selected':''} onClick={()=>toggle(o)} key={o}>{selected.includes(o)?'✓ ':''}{o}</button>)}</div>
      <div className="builder-next-step"><div><span>DEPOIS DE BLOQUEAR</span><b>Seu card fica protegido e você poderá entrar no torneio.</b></div><small>🔐 Seu adversário nunca vê suas escolhas antes da hora.</small></div>
      <div className="card-actions"><button className="primary big-btn" onClick={createCard} disabled={selected.length!==cr.quantity_options}>🔒 {selected.length===cr.quantity_options?'Bloquear meu card':'Escolha '+(cr.quantity_options-selected.length)+' opção(ões)'}</button>{t.available_cards?.length>0&&<select value={cardId} onChange={e=>setCardId(e.target.value)}><option value="">Usar um card já criado</option>{t.available_cards.map(c=><option key={c.card_id} value={c.card_id}>{c.options.join(' · ')}</option>)}</select>}</div>
      {readyToJoin&&<div className="card-ready-box"><div><span className="ready-check">✓</span><div><b>SEU CARD ESTÁ PRONTO</b><small>{cardId?'Card recém-criado':myCard?'Card reservado nesta edição':'Card disponível para uso'}</small></div></div><strong>{t.rules?.entry_fee>0?`Entrada: ${t.rules.entry_fee} Farejadores`:'Entrada gratuita'}</strong></div>}
      <button className="join-cta" onClick={join} disabled={!readyToJoin}><span>{readyToJoin?'2 · Participar agora':'2 · Primeiro bloqueie seu card'}</span><b>{t.rules?.entry_fee>0?`${t.rules.entry_fee} Farejadores`:'GRÁTIS'} →</b></button>
      <div className="builder-footnote"><span>✓ Card compatível com este torneio</span><span>✓ 1 inscrição por jogador</span><span>✓ Depois de entrar, você só precisa aguardar o duelo</span></div>
    </div>}

    {t.status==='open'&&!canBuild&&isParticipant&&<div className="join-confirmed-card"><span>🎟️</span><div><small>VOCÊ JÁ ESTÁ NESTA EDIÇÃO</small><h2>Inscrição confirmada</h2><p>Seu card está reservado. Agora é só aguardar o início da batalha.</p></div><b>{full?'⚔️ TORNEIO LOTADO':'✓ PRONTO'}</b></div>}
    {t.status==='open'&&!isParticipant&&reg===0&&<div className="waiting-arena"><div className="waiting-icon">⏳</div><h2>Inscrições encerradas</h2><p>A edição não está mais recebendo novos jogadores.</p></div>}

    {t.status==='open'&&<div className="arena-countdown"><div><span className="eyebrow">{full?'TORNEIO LOTADO':'INSCRIÇÕES ABERTAS'}</span><h2>{clock(full?start:reg)}</h2><p>{full?'A batalha começa quando o cronômetro zerar.':'Tempo restante para entrar nesta edição.'}</p></div><div className="countdown-ring">{full?'⚔':'⏱'}</div></div>}

    {isLive&&<div className="duel-stage">
      <div className="duel-topline"><span className="live-badge"><span className="live-dot"></span> DUELO AO VIVO</span><span className="duel-clock">⏱ {clock(deadline)}</span></div>
      {my.replay_number>0&&<div className="replay-strip">🤝 <div><b>REPLAY {my.replay_number}</b><span>O duelo empatou. Você continua na disputa — jogue novamente.</span></div></div>}
      <div className="players-faceoff"><div className="fighter"><div className="fighter-avatar me">{initials(meName)}</div><small>VOCÊ</small><b>{meName||'Você'}</b><span className="fighter-tag">ATAQUES {attemptsLeft}</span></div><div className="vs-mark"><span>VS</span><small>ROUND {my.round||1}</small></div><div className="fighter opponent"><div className="fighter-avatar"><span>?</span></div><small>ADVERSÁRIO</small><b>{opponent||'Oponente'}</b><span className="fighter-tag">CARD OCULTO</span></div></div>
      <div className={`secret-card ${attackFx||''}`}>{attackFx&&attackFx!=="launch"&&<div className={`attack-fx ${attackFx}`}>{attackFx==="hit"?'🎯 ACERTO!':attackFx==="miss"?'× ERRO':'!'}</div>}<div className="secret-card-top"><span>🎴 CARD INIMIGO</span><span>{attemptsLeft} {attemptsLeft===1?'ATAQUE':'ATAQUES'} RESTANTES</span></div><div className="card-mystery"><div className="card-symbol">⌕</div><strong>DESCUBRA</strong><span>Escolha uma opção para atacar o card adversário</span></div></div>
      {own.length>0&&<div className="attack-history">{own.map(a=><div key={a.attempt} className={a.correct?'hit':'miss'}><span>{a.correct?'✓':'×'}</span><div><b>{a.option}</b><small>{a.correct?'ACERTO!':'Não estava no card'}</small></div></div>)}</div>}
      {my.revealed_opponent_card&&<div className="revealed-card"><span>🎯 CARD REVELADO</span><b>{my.revealed_opponent_card.join(' · ')}</b></div>}
      {attemptsLeft>0?<form onSubmit={sendGuess} className="attack-form"><label><span>SELECIONE SEU ATAQUE</span><select value={guess} onChange={e=>setGuess(e.target.value)} required><option value="">Escolha uma opção...</option>{options.filter(o=>!used.includes(o)).map(o=><option key={o} value={o}>{o}</option>)}</select></label><button className={`attack-button ${attacking?'is-attacking':''}`} disabled={!guess||attacking}>{attacking?'⚡ ENVIANDO...':'⚡ ATACAR'}</button></form>:<div className="notice center-notice">🛡️ Seus ataques acabaram. Aguarde a jogada do adversário.</div>}
      {lastGuess&&<div className="last-attack">Último ataque enviado: <b>{lastGuess}</b></div>}<small className="server-note">🔐 O card adversário permanece protegido pelo servidor até a resolução do duelo.</small>
    </div>}
    {t.status==='live'&&!my&&isParticipant&&<div className="waiting-arena"><div className="waiting-icon">⚔️</div><span className="eyebrow">AGUARDE SUA VEZ</span><h2>{state.state==='advanced'?'Você avançou — próxima rodada em preparação':'Seu próximo duelo está sendo preparado'}</h2><p>{state.message||'A rodada está acontecendo. Assim que sua partida estiver pronta, ela aparecerá aqui automaticamente.'}</p></div>}
    {msg&&<div className="notice arena-message">{msg}</div>}

    {finishedMatch&&<section className={`duel-result ${matchWon?'win':matchDraw?'draw':'loss'}`}><div className="result-glow"></div>{matchWon&&<div className="confetti" aria-hidden="true">{Array.from({length:18},(_,i)=><i key={i}></i>)}</div>}<div className="result-icon">{resultIcon}</div><span className="eyebrow">RESULTADO DO DUELO · RODADA {finishedMatch.round}</span><h2>{resultTitle}</h2><p>{resultReasonLabel(finishedMatch.result_reason)}</p>{matchDraw&&<div className="result-next-step"><b>🤝 VOCÊ NÃO FOI ELIMINADO</b><span>O servidor abriu um replay para decidir quem avança. Nenhuma nova inscrição é necessária.</span></div>}{matchWon&&<div className="result-next-step success"><b>🏆 VOCÊ AVANÇOU</b><span>Sua vitória foi registrada. Aguarde a próxima rodada na Arena.</span></div>}{!matchWon&&!matchDraw&&<div className="result-next-step danger"><b>💥 ELIMINAÇÃO CONFIRMADA</b><span>Seu torneio terminou para você. Você pode acompanhar a classificação e voltar à Arena.</span></div>}<div className="result-versus"><div className={matchWon?'winner-side':''}><small>VOCÊ</small><b>{user?.username||'Você'}</b></div><span>VS</span><div className={!matchWon&&!matchDraw?'winner-side':''}><small>ADVERSÁRIO</small><b>{opponent||'Oponente'}</b></div></div><div className="result-actions">{matchDraw&&<button className="primary big-btn" onClick={()=>setTab('bracket')}>🤝 Acompanhar replay</button>}{matchWon&&<button className="primary big-btn" onClick={()=>setTab('bracket')}>🏆 Ver minha chave</button>}{!matchWon&&!matchDraw&&<button className="primary big-btn" onClick={()=>setTab('results')}>📊 Ver classificação</button>}<button className="ghost-btn" onClick={()=>setTab('timeline')}>Ver histórico</button></div><small className="server-note">Resultado confirmado pelo servidor · nenhum ponto ou prêmio é calculado no navegador.</small></section>}

    <div className="matches-section"><div className="section-head"><div><span className="eyebrow">VISÃO GERAL</span><h2>Todos os duelos</h2></div><span>{t.matches?.filter(m=>m.status==='finished').length||0} finalizados</span></div><MatchTable matches={t.matches} userId={user?.id}/></div>
   </section>
   <aside className="arena-sidebar"><section className="panel side-stat"><span className="eyebrow">🎴 CARD</span><h3>{cr.theme_name||'Tema do torneio'}</h3><div className="side-metric"><b>{cr.quantity_options}</b><span>escolhas</span><b>{cr.quantity_answers}</b><span>ataques</span></div><small>{cr.quantity_options} escolhas dentre {options.length} opções disponíveis.</small></section><section className="panel side-clock"><span className="eyebrow">⏱️ TEMPO</span><div className="side-time">{t.status==='open'?clock(full?start:reg):t.status==='live'?clock(deadline):'—'}</div><p>{t.status==='open'?(full?'até a batalha começar':'até fechar a inscrição'):'rodadas avançam automaticamente'}</p></section><section className="panel prize-breakdown"><span className="eyebrow">🎁 PREMIAÇÃO</span><div><b>🥇 {t.rules.prize_first}%</b><span>1º lugar</span></div><div><b>🥈 {t.rules.prize_second}%</b><span>2º lugar</span></div><div><b>{t.rules.organizer_percent}%</b><span>organizador</span></div><div><b>{t.rules.system_percent}%</b><span>sistema</span></div></section></aside>
  </div>}
  {tab==='bracket'&&<section className="panel tab-panel bracket-panel-v8"><div className="tab-title"><span className="eyebrow">CAMINHO ATÉ A VITÓRIA</span><h2>🏆 Chave do torneio</h2><p>Acompanhe quem está avançando. Empates aparecem como replay, sem eliminar o jogador.</p></div><Bracket matches={t.matches}/></section>}
  {tab==='players'&&<section className="panel tab-panel players-panel-v8"><div className="tab-title"><span className="eyebrow">QUEM ESTÁ NA ARENA</span><h2>👥 Participantes</h2><p>Os jogadores confirmados nesta edição.</p></div><div className="players players-v8">{t.participants.map((p,i)=><div className="player-row-v8" key={p.entry_id}><b className="player-number">#{i+1}</b><span className="mini-avatar">{initials(p.username)}</span><div className="player-copy-v8"><strong>{p.username}</strong><small>{String(p.user_id)===String(user?.id)?'Você · ':i===0?'Primeiro a entrar · ':''}{p.status==='confirmed'?'Pronto para jogar':'Aguardando confirmação'}</small></div><span className="player-state-v8">{p.status==='confirmed'?'✓ CONFIRMADO':'⏳ AGUARDANDO'}</span></div>)}</div></section>}
  {tab==='results'&&<section className="panel tab-panel results-panel-v8"><div className="tab-title"><span className="eyebrow">PLACAR FINAL</span><h2>📊 Classificação e premiação</h2><p>O resultado oficial e as recompensas desta edição.</p></div>{t.my_payments?.length>0&&<div className="winner-banner-v8"><div className="winner-icon-v8">🏆</div><div><span>RECOMPENSA CONFIRMADA</span><b>Você recebeu {t.my_payments.reduce((sum,p)=>sum+Number(p.amount||0),0)} Farejadores</b><small>{t.my_payments.map(p=>`${p.percentage}% · ${p.type}`).join('  •  ')}</small></div></div>}{t.results.length?<div className="results results-v8">{t.results.map(r=><div className={`result-row-v8 ${Number(r.position)===1?'champion':''}`} key={r.user_id}><b className="result-position-v8">#{r.position}</b><span className="result-avatar-v8">{initials(r.username)}</span><div className="result-user-v8"><strong>{r.username}</strong><small>{Number(r.position)===1?'🏆 Campeão da edição':Number(r.position)===2?'🥈 Vice-campeão':`${r.position}º lugar`}</small></div><div className="result-score-v8"><b>{r.points}</b><small>PTS</small><span>+{r.xp} XP</span></div></div>)}</div>:<div className="empty-result-v8"><span>📊</span><b>Classificação ainda não fechada</b><small>Os resultados oficiais aparecem quando o torneio terminar.</small></div>}</section>}
  {tab==='timeline'&&<section className="panel tab-panel timeline-panel-v8"><div className="tab-title"><span className="eyebrow">HISTÓRICO DA BATALHA</span><h2>🕒 Linha do tempo</h2><p>Inclui empates, replays, eliminações e avanços.</p></div><div className="timeline timeline-v8">{events.map((e,i)=><div className={`timeline-item timeline-item-v8 ${e.type==='match_replay'?'timeline-replay':''}`} key={e.event_id}><span className="timeline-dot-v8">{e.type==='match_replay'?'🤝':i===0?'✦':'•'}</span><div><b>{eventName(e.event_type||e.type)}</b><small>{new Date(e.created_at).toLocaleString('pt-BR')}</small>{e.payload?.message&&<span>{e.payload.message}</span>}</div></div>)}</div></section>}
 </div>
}

function MatchTable({matches=[],userId}){return <div className="matches matches-v8">{matches.map(m=>{const mine=String(m.player1_id)===String(userId)||String(m.player2_id)===String(userId);const winnerMine=mine&&String(m.winner_id)===String(userId);const draw=!m.winner&&m.status==='finished';return <div className={`match match-v8 ${m.status} ${mine?'mine':''} ${draw?'draw':''}`} key={`${m.match_id}-${m.replay_number}`}><span className="match-round-v8">R{m.round} · #{m.match_number}{m.replay_number>0&&<em>REPLAY {m.replay_number}</em>}</span><div className="match-players-v8"><b className={String(m.player1_id)===String(userId)?'me-player':''}>{m.player1||'BYE'}</b><i>VS</i><b className={String(m.player2_id)===String(userId)?'me-player':''}>{m.player2||'BYE'}</b></div><strong>{m.status==='finished'?(draw?'🤝 Empate · replay':winnerMine?'🏆 Você avança':m.winner?`💥 ${m.winner} avança`:'Finalizado'):'⏳ Em andamento'}</strong></div>})}</div>}
function Bracket({matches=[]}){const rounds=[...new Set(matches.map(m=>m.round))];return <div className="bracket bracket-v8">{rounds.map(r=><section key={r}><div className="bracket-round-title"><span>ROUND {r}</span><h3>{r===1?'Primeira rodada':r===rounds.length?'🏆 Decisão':`Rodada ${r}`}</h3></div>{matches.filter(m=>m.round===r).map(m=><div className={`bracket-match bracket-match-v8 ${!m.winner&&m.status==='finished'?'draw-match':''}`} key={`${m.match_id}-${m.replay_number}`}><div className={m.winner===m.player1?'bracket-player winner':'bracket-player'}><span>{initials(m.player1||'B')}</span><b>{m.player1||'BYE'}</b>{m.winner===m.player1&&<em>✓</em>}</div><div className="bracket-vs">{m.replay_number>0?'🤝':'VS'}</div><div className={m.winner===m.player2?'bracket-player winner':'bracket-player'}><span>{initials(m.player2||'B')}</span><b>{m.player2||'BYE'}</b>{m.winner===m.player2&&<em>✓</em>}</div><small>{m.replay_number>0?`🤝 Replay ${m.replay_number} · ninguém eliminado`:m.status==='finished'?(m.winner?`🏆 ${m.winner} avança`:'🤝 Empate'):'⏳ Aguardando duelo'}</small></div>)}</section>)}</div>}
